/**:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    min_particles: 500
    max_particles: 2000
    laser_model_type: "likelihood_field"
    laser_likelihood_max_dist: 2.0
    laser_max_range: 10.0  # Should match your scan max range
    laser_min_range: 0.1   # Should match your scan min range
    update_min_d: 0.05
    update_min_a: 0.1
    transform_tolerance: 0.5
    initial_pose:
      x: 0.0
      y: 0.0
      theta: 0.0
      covariance: [0.25, 0.0, 0.0, 0.0, 0.0, 0.0,
                  0.0, 0.25, 0.0, 0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.06853892326654787]