amcl:
  ros__parameters:
    use_sim_time: false
    # Motion model noise parameters
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    alpha1: 0.0001    # Rotation noise from rotation  
    alpha2: 0.0001    # Rotation noise from translation  
    alpha3: 0.0002    # Translation noise from translation  
    alpha4: 0.0001    # Translation noise from rotation  
    
    # Particle filter settings
    min_particles: 100
    max_particles: 500
    recovery_alpha_slow: 0.001
    recovery_alpha_fast: 0.3
    
    # Laser model settings
    laser_model_type: "likelihood_field"
    laser_max_range: 10.0           # Must match your scan publisher
    laser_min_range: 0.1            # Must match your scan publisher
    
    max_beams: 60            

    #z_hit: 0.1
    #z_rand: 0.9
    z_hit: 0.9 # Weight for hit component
    z_rand: 0.1 # Weight for the random component
    sigma_hit: 0.1 # Standard deviation for Gaussian model

    laser_likelihood_max_dist: 1.5

    #odom topic
    odom_frame_id: "odom"
    #odom_frame_id: "odom"
    base_frame_id: "base_link"
    global_frame_id: "map"

    
    # Update thresholds
    update_min_d: 0.05    # Minimum translational movement to update filter
    update_min_a: 0.05     # Minimum angular movement to update filter
    
    # Tolerance
    transform_tolerance: 0.1
    transform_cache_time: 20.0
    use_pose_with_covariance_stamped: false
    
    # Initial pose (with covariance)
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      theta: 0.0
      covariance: [0.25, 0.0, 0.0, 0.0, 0.0, 0.0,
                  0.0, 0.25, 0.0, 0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.068]

    print_level: 2
   