ekf_localization_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.25
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    

    odom0: /zed/zed_node/odom
    odom0_config: [true, true, false,   # x, y, z position
                   false, false, true,  # roll, pitch, yaw
                   false, false, false, # x, y, z velocity
                   false, false, true,  # roll, pitch, yaw velocity
                   false, false, false] # x, y, z acceleration

    odom0_differential: false
    odom0_queue_size: 2
    odom0_relative: true
    odom0_nodelay: false

    odom1: /vesc/odom
    odom1_config: [false, false, false, # x, y, z position
                   false, false, false, # roll, pitch, yaw
                   true, true, false,   # x, y, z velocity
                   false, false, false, # roll, pitch, yaw velocity
                   false, false, false] # x, y, z acceleration

    odom1_differential: false
    odom1_relative: false
    odom1_queue_size: 2
    odom1_nodelay: false

    imu0: sensors/imu/raw
    imu0_config: [false, false, false,   # x, y, z position
                  false,  false,  true,  # roll, pitch, yaw
                  false, false, false,   # x, y, z velocity
                  false,  false,  true,  # roll, pitch, yaw velocity
                  false,  false,  false] # x, y, z acceleration
                  
    imu0_nodelay: false
    imu0_differential: false
    imu0_relative: true
    imu0_queue_size: 5
    imu0_remove_gravitational_acceleration: true

  
