ekf_localization_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.25
    two_d_mode: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    

    odom0: /zed/zed_node/odom
    odom0_config: [true, true, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]

    odom0_differential: false
    odom0_relative: false

    odom1: /vesc/odom
    odom1_config: [true, true, false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom1_differential: true
    odom1_relative: false