ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    two_d_mode: true
    
    # Frame IDs
    odom_frame: odom
    base_link_frame: zed_camera_link
    world_frame: odom
    
    # Input sources
    odom0: /zed/zed_node/odom
    odom1: /odom
    
    # Configure which variables to fuse from each source
    odom0_config: [true,  true,  false,  # X, Y, Z
                   false, false, true,   # roll, pitch, yaw
                   false, false, false,   # X vel, Y vel, Z vel
                   false, false, true,    # roll vel, pitch vel, yaw vel
                   false, false, false]   # X accel, Y accel, Z accel
    
    odom1_config: [false, false, false,  # X, Y, Z
                   false, false, false,
                   true,  true,  false,  # Linear velocities
                   false, false, true,   # Angular velocities
                   false, false, false]
    
    # Process noise covariance 
    process_noise_covariance: [0.05, 0,    0,    0,    0,    0,
                               0,    0.05, 0,    0,    0,    0,
                               0,    0,    0.06, 0,    0,    0,
                               0,    0,    0,    0.03, 0,    0,
                               0,    0,    0,    0,    0.03, 0,
                               0,    0,    0,    0,    0,    0.06]